### ISSUE TITLE
Crash compiling xlocale.c

### ISSUE THREAD

**Issue by RichardsonAlex** [CTSRD-CHERI/clang#108]
Assertion failed: (getActiveBits() <= 64 && "Too many bits for uint64_t"), function getZExtValue, file /home/alr48/cheri/sources/llvm/include/llvm/ADT/APInt.h, line 1331.

`/home/alr48/cheri/output/sdk256/bin/clang-3.8 -cc1 -triple cheri-unknown-freebsd -emit-obj -disable-free -main-file-name xlocale.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-feature +soft-float -target-abi sandbox -msoft-float -mfloat-abi soft -mllvm -mxgot -mllvm -mips-ssection-threshold=0 -dwarf-column-info -debug-info-kind=standalone -dwarf-version=2 -sys-header-deps -D FORCE_C_LOCALE -D FORCE_UTC_TZ -O2 -Wno-cast-align -Wno-error -Wcapability-to-integer-cast -Wsystem-headers -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wunused-parameter -Wcast-align -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wold-style-definition -Wno-pointer-sign -Wmissing-variable-declarations -Wthread-safety -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-function -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-function -std=gnu99 -fconst-strings -ferror-limit 19 -fmessage-length 0 -ftls-model=local-exec -fobjc-runtime=gnustep -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -cheri-linker -x c /tmp/xlocale-1d9a31.c`
Script: https://gist.github.com/RichardsonAlex/c35e88b1429c64a006c91eb8dc6c8911
Source: https://gist.github.com/RichardsonAlex/4ea715ca1e4a0b8de81371cc8c196cf1

Backtrace:
```
(gdb) bt
#0  0x0000000806e1935a in thr_kill () from /lib/libc.so.7
#1  0x0000000806e19346 in raise () from /lib/libc.so.7
#2  0x0000000806e192c9 in abort () from /lib/libc.so.7
#3  0x0000000806e7ff91 in __assert () from /lib/libc.so.7
#4  0x000000000086e82d in llvm::APInt::getZExtValue (this=0x7fffffff1a98) at /home/alr48/cheri/sources/llvm/include/llvm/ADT/APInt.h:1331
#5  0x0000000004674fbf in (anonymous namespace)::PointerExprEvaluator::VisitCastExpr (this=0x7fffffff1d48, E=0x807acc968) at /home/alr48/cheri/sources/llvm/tools/clang/lib/AST/ExprConstant.cpp:4991
#6  0x0000000004674a18 in clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::PointerExprEvaluator, bool>::VisitExplicitCastExpr (this=0x7fffffff1d48, S=0x807acc968)
    at tools/clang/include/clang/AST/StmtNodes.inc:335
#7  0x0000000004632738 in clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::PointerExprEvaluator, bool>::VisitCStyleCastExpr (this=0x7fffffff1d48, S=0x807acc968)
    at tools/clang/include/clang/AST/StmtNodes.inc:339
#8  0x000000000462f84b in clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::PointerExprEvaluator, bool>::Visit (this=0x7fffffff1d48, S=0x807acc968)
    at tools/clang/include/clang/AST/StmtNodes.inc:339
#9  0x000000000463381d in (anonymous namespace)::ExprEvaluatorBase<(anonymous namespace)::PointerExprEvaluator>::VisitParenExpr (this=0x7fffffff1d48, E=0x807acc990)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/AST/ExprConstant.cpp:4061
#10 0x000000000462fe2f in clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::PointerExprEvaluator, bool>::Visit (this=0x7fffffff1d48, S=0x807acc990)
    at tools/clang/include/clang/AST/StmtNodes.inc:675
#11 0x000000000462ec2f in EvaluatePointer (E=0x807acc990, Result=..., Info=...) at /home/alr48/cheri/sources/llvm/tools/clang/lib/AST/ExprConstant.cpp:4893
#12 0x00000000046522f4 in (anonymous namespace)::IntExprEvaluator::VisitBinaryOperator (this=0x7fffffff3298, E=0x807acc9c8) at /home/alr48/cheri/sources/llvm/tools/clang/lib/AST/ExprConstant.cpp:7242
#13 0x0000000004650618 in clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::IntExprEvaluator, bool>::VisitBinEQ (this=0x7fffffff3298, S=0x807acc9c8)
    at /home/alr48/cheri/sources/llvm/tools/clang/include/clang/AST/StmtVisitor.h:128
#14 0x000000000464ebc0 in clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::IntExprEvaluator, bool>::Visit (this=0x7fffffff3298, S=0x807acc9c8)
    at /home/alr48/cheri/sources/llvm/tools/clang/include/clang/AST/StmtVisitor.h:61
#15 0x00000000046577fd in (anonymous namespace)::ExprEvaluatorBase<(anonymous namespace)::IntExprEvaluator>::VisitParenExpr (this=0x7fffffff3298, E=0x807acc9f0)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/AST/ExprConstant.cpp:4061
#16 0x000000000464fb6f in clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::IntExprEvaluator, bool>::Visit (this=0x7fffffff3298, S=0x807acc9f0)
    at tools/clang/include/clang/AST/StmtNodes.inc:675
#17 0x000000000461ca36 in Evaluate (Result=..., Info=..., E=0x807acc9f0) at /home/alr48/cheri/sources/llvm/tools/clang/lib/AST/ExprConstant.cpp:8653
---Type <return> to continue, or q <return> to quit---
#18 0x0000000004618e46 in EvaluateAsRValue (Info=..., E=0x807acc9f0, Result=...) at /home/alr48/cheri/sources/llvm/tools/clang/lib/AST/ExprConstant.cpp:8742
#19 0x0000000004618acb in clang::Expr::EvaluateAsRValue (this=0x807acc9f0, Result=..., Ctx=...) at /home/alr48/cheri/sources/llvm/tools/clang/lib/AST/ExprConstant.cpp:8797
#20 0x0000000004619029 in clang::Expr::EvaluateAsBooleanCondition (this=0x807acc9f0, Result=@0x7fffffff36ff: false, Ctx=...) at /home/alr48/cheri/sources/llvm/tools/clang/lib/AST/ExprConstant.cpp:8805
#21 0x0000000003b9b1f1 in (anonymous namespace)::SequenceChecker::EvaluationTracker::evaluate (this=0x7fffffff3788, E=0x807acc9f0, Result=@0x7fffffff36ff: false)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/Sema/SemaChecking.cpp:7984
#22 0x0000000003b9d0fb in (anonymous namespace)::SequenceChecker::VisitAbstractConditionalOperator (this=0x7fffffff38b8, CO=0x807acca88)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/Sema/SemaChecking.cpp:8241
#23 0x0000000003b98db8 in clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::SequenceChecker, void>::VisitConditionalOperator (this=0x7fffffff38b8, S=0x807acca88)
    at tools/clang/include/clang/AST/StmtNodes.inc:117
#24 0x0000000003b96927 in clang::StmtVisitorBase<clang::make_ptr, (anonymous namespace)::SequenceChecker, void>::Visit (this=0x7fffffff38b8, S=0x807acca88) at tools/clang/include/clang/AST/StmtNodes.inc:117
#25 0x0000000003b7f4c7 in (anonymous namespace)::SequenceChecker::SequenceChecker (this=0x7fffffff38b8, S=..., E=0x807acca88, WorkList=...)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/Sema/SemaChecking.cpp:8075
#26 0x0000000003b7f3f0 in clang::Sema::CheckUnsequencedOperations (this=0x807913000, E=0x807acca88) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Sema/SemaChecking.cpp:8314
#27 0x0000000003b7f55f in clang::Sema::CheckCompletedExpr (this=0x807913000, E=0x807acca88, CheckLoc=..., IsConstexpr=false) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Sema/SemaChecking.cpp:8321
#28 0x0000000003ea27e9 in clang::Sema::ActOnFinishFullExpr (this=0x807913000, FE=0x807acca88, CC=..., DiscardedValue=false, IsConstexpr=false, IsLambdaInitCaptureInitializer=false)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/Sema/SemaExprCXX.cpp:6710
#29 0x0000000003c20e15 in clang::Sema::AddInitializerToDecl (this=0x807913000, RealDecl=0x807acc890, Init=0x807acca88, DirectInit=false, TypeMayContainAuto=false)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/Sema/SemaDecl.cpp:9401
#30 0x000000000375733e in clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes (this=0x80788f200, D=..., TemplateInfo=..., FRI=0x0)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/ParseDecl.cpp:2048
#31 0x000000000375558c in clang::Parser::ParseDeclGroup (this=0x80788f200, DS=..., Context=7, DeclEnd=0x7fffffff7530, FRI=0x0) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/ParseDecl.cpp:1809
#32 0x0000000003750a97 in clang::Parser::ParseSimpleDeclaration (this=0x80788f200, Context=7, DeclEnd=..., Attrs=..., RequireSemi=true, FRI=0x0)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/ParseDecl.cpp:1541
#33 0x00000000037507fd in clang::Parser::ParseDeclaration (this=0x80788f200, Context=7, DeclEnd=..., attrs=...) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/ParseDecl.cpp:1486
#34 0x00000000037e70a5 in clang::Parser::ParseStatementOrDeclarationAfterAttributes (this=0x80788f200, Stmts=..., OnlyStatement=false, TrailingElseLoc=0x0, Attrs=...)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/ParseStmt.cpp:207
#35 0x00000000037e64fd in clang::Parser::ParseStatementOrDeclaration (this=0x80788f200, Stmts=..., OnlyStatement=false, TrailingElseLoc=0x0)
---Type <return> to continue, or q <return> to quit---
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/ParseStmt.cpp:106
#36 0x00000000037ed79c in clang::Parser::ParseCompoundStatementBody (this=0x80788f200, isStmtExpr=false) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/ParseStmt.cpp:960
#37 0x00000000037ee244 in clang::Parser::ParseFunctionStatementBody (this=0x80788f200, Decl=0x807acc7d0, BodyScope=...) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/ParseStmt.cpp:1904
#38 0x00000000037323ca in clang::Parser::ParseFunctionDefinition (this=0x80788f200, D=..., TemplateInfo=..., LateParsedAttrs=0x7fffffff8480)
    at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/Parser.cpp:1145
#39 0x00000000037551b4 in clang::Parser::ParseDeclGroup (this=0x80788f200, DS=..., Context=0, DeclEnd=0x0, FRI=0x0) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/ParseDecl.cpp:1756
#40 0x00000000037315c4 in clang::Parser::ParseDeclOrFunctionDefInternal (this=0x80788f200, attrs=..., DS=..., AS=clang::AS_none) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/Parser.cpp:927
#41 0x0000000003730de0 in clang::Parser::ParseDeclarationOrFunctionDefinition (this=0x80788f200, attrs=..., DS=0x0, AS=clang::AS_none) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/Parser.cpp:943
#42 0x000000000373069f in clang::Parser::ParseExternalDeclaration (this=0x80788f200, attrs=..., DS=0x0) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/Parser.cpp:801
#43 0x000000000372f7e9 in clang::Parser::ParseTopLevelDecl (this=0x80788f200, Result=...) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/Parser.cpp:593
#44 0x0000000003728ada in clang::ParseAST (S=..., PrintStats=false, SkipFunctionBodies=false) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Parse/ParseAST.cpp:161
#45 0x0000000002f6d39b in clang::ASTFrontendAction::ExecuteAction (this=0x8078510f0) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:538
#46 0x000000000346f889 in clang::CodeGenAction::ExecuteAction (this=0x8078510f0) at /home/alr48/cheri/sources/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:790
#47 0x0000000002f6c9c0 in clang::FrontendAction::Execute (this=0x8078510f0) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:439
#48 0x0000000002ef1e12 in clang::CompilerInstance::ExecuteAction (this=0x807831140, Act=...) at /home/alr48/cheri/sources/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:838
#49 0x00000000030d66fa in clang::ExecuteCompilerInvocation (Clang=0x807831140) at /home/alr48/cheri/sources/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:222
#50 0x000000000083c317 in cc1_main (Argv=..., Argv0=0x7fffffffe560 "/home/alr48/cheri/output/sdk256/bin/clang-3.8", MainAddr=0x82a2f0 <GetExecutablePath(char const*, bool)>)
    at /home/alr48/cheri/sources/llvm/tools/clang/tools/driver/cc1_main.cpp:116
#51 0x000000000082d169 in ExecuteCC1Tool (argv=..., Tool=...) at /home/alr48/cheri/sources/llvm/tools/clang/tools/driver/driver.cpp:301
#52 0x000000000082af95 in main (argc_=86, argv_=0x7fffffffdfd0) at /home/alr48/cheri/sources/llvm/tools/clang/tools/driver/driver.cpp:366
```

**Comment by davidchisnall** [comment]
Any chance of a reduced test case for this?

**Comment by RichardsonAlex** [comment]
Based on the backtrace looks like it could be caused by this function? casting 42 to void*?

```
static void init_key(void)
{

	pthread_key_create(&locale_info_key, xlocale_release);
	pthread_setspecific(locale_info_key, (void*)42);
	if (pthread_getspecific(locale_info_key) == (void*)42) {
		pthread_setspecific(locale_info_key, 0);
	} else {
		fake_tls = 1;
	}
	/* At least one per-thread locale has now been set. */
	__has_thread_locale = 1;
	__detect_path_locale();
}
```

**Comment by davidchisnall** [comment]
Minimal test case:
```C
__capability void *x=  (__capability void*)-1;
```
